baseurl = "https://hasingh.us"
title = "harshpreet singh"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"


[pagination]
    pagerSize = 20

[services]
[services.disqus]
shortname = "hasingh-us"

[markup.highlight]
style = "github-dark"

[params]
  author = "Harshpreet Singh"
  info = "Software Enginner"
  description = "Harshpreet Singh's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/blog-pic.JPG"
  #gravatar = "john.doe@example.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2019

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/harshpreet93/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
